title: My blog
theme: minima
author: Victoria Akpan
email: veedahv55@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This a blog create by Victoria Akpan and it is awesome! This  blog is all about frontend development an my journey so far!! for your nw sit hr. You can it this
  line in _onfig.yml. It will appear in your document head meta (for
  Google search results) an in your feed.xml site dscription.

# social links
twitter_username: me_veey # DO NOT include the @ character, or else the build will fail!
github_username:  veedahv  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
